kind: ResourceQuota
apiVersion: v1
metadata:
  name: quota
  namespace: test
  labels:
    quota-tier: large
  annotations:
    kubernetes.io/quota-tier: large
spec:
  hard:
    cpu: '16'
    memory: 32Gb
    limits.cpu: '32'
    limits.memory: 64Gb
  scopes:
  - NotTerminating
