kind: ResourceQuota
apiVersion: v1
metadata:
  name: quota
  namespace: test
  labels:
    quota-tier: small
  annotations:
    kubernetes.io/quota-tier: small
spec:
  hard:
    cpu: '6'
    memory: 16Gb
    limits.cpu: '12'
    limits.memory: 32Gb
  scopes:
  - NotTerminating
