kind: ResourceQuota
apiVersion: v1
metadata:
  name: quota
  namespace: {{ namespace }}
  labels:
    quota-tier: {{ tier }}
  annotations:
    kubernetes.io/quota-tier: {{ tier }}
spec:
  hard:
    cpu: {{ cpu }}
    memory: {{ memory }}
    limits.cpu: {{ burstcpu }}
    limits.memory: {{ burstmem }}
  scopes:
    - NotTerminating